#!/usr/bin/python
import sys

replace_arr = [
["""border="1" """,""],
[ "</head> ","""<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>"""],

[ "</body>" , """
</div>
</div>
<!-- linbox footer section -->
<div id="linbox_footer" class="small">
  <div class="left" style="margin:0px 4px 0px 4px;">

    <span style="font-weight:bold;">Linbox Metz</span>: +33 (0)3 87 50 87 90 -
    <span style="font-weight:bold;">Paris</span>: +33 (0)1 48 57 62 33 -
    <a href="mailto:info&#64;linbox.com">info&#64;linbox.com</a>
  </div>
  <div class="right" style="margin:0px 4px 0px 4px;">&copy;&nbsp; 1996-2006 Linbox FAS&nbsp;</div><br/>
</div
</body>"""],

[ "<body>" , """<body>  <style type="text/css">
/* BODY */
body {
  background-color: #8E9CA7;
  color: #333;
  margin: 0;
  font-family: Verdana, Lucida, Geneva, Helvetica, Arial, sans-serif;
  font-size: 12px;
  padding: 0px;
}
/* BODY */


/* MAIN */
#main {
  padding: 1px;
  margin: 0px;
  background-color: #F2F2F2;
  min-height: 400px;
}
/* MAIN */


/* CONTENT */
#content {
  margin: 20px;
  padding: 20px;
  background-color: #FFF;
  -moz-border-radius: 10px;
  border: 1px solid #A0A0A0;
}
/* CONTENT */


#ctxtnav {
    display: none;
}

/* METANAV BAR */
#metanav {
  background: #333 url(http://lds.linbox.org/custom/bg_header.gif) 0 0 repeat-x;
  border: 1px solid;
  border-color: black;
  height:26px;
}
#metanav a {
  color: white;
}
#metanav a:hover {
  color: black;
}
#metanav ul  {
  position: relative;
  top: 7px;
}
/* METANAV BAR */


/* MAINNAV BAR */
#mainnav {
  display: block;
  margin: 0px;
  padding: 0px;
  border: none;
  border-bottom: 1px solid #B2B2B2;
  background: none;
  background: white;
  height: 34px;
}

#mainnav :link, #mainnav :visited {
  position: relative;
  margin: 0px;
  top: 10px;
  background-color: #FFFFFF ;
  background-image: none;
  font-size: 12px;
  color: #000;
  padding: 10px;
}

#mainnav :link:hover, #mainnav :visited:hover {
  background-color: #F2F2F2;
}

#mainnav .active:link, #mainnav .active:visited {
  background-image: none;
  background-color: #F2F2F2;
  border-right: 1px solid #F2F2F2;
  border-bottom: 1px solid #F2F2F2;
  color: #000;
  font-weight: bold;
}
/* MAINNAV BAR */


/* Link styles */
:link, :visited {
	        color: #EE5010;
}

:link:hover, :visited:hover {
	        color: #EE5010;
}

/* Forms */
input[type=button]:hover, input[type=submit]:hover, input[type=reset]:hover {
	         background: #EE5010;
}


/* SEARCH BOX AND BUTTON */
#search {
  float: right;
  position: relative;
  top: 0px;
  display: none;
}
/* SEARCH BOX AND BUTTON */


/* MAIN LOGO */
#logo {
  position: absolute;
  float: left;
  display: none;
}

#logolinbox {
  position: absolute;
  top: 0px;
  left: 0px;
}
/* MAIN LOGO */


/* LINBOX FOOTER */
#footer {
  display: none;
}

#linbox_footer {
  font: normal 10px verdana,arial,helvetica,sans-serif;
  height: 15px;
  padding: 4px;
  border-top: 1px solid #000000;
  border-bottom: 1px;
  background-color: #CCCCCC;
}

.right  { float: right; }
.left   { float: left; }
/* LINBOX FOOTER */


/* LINBOX LEFT MENU */
#menu_left {
 width: 120px;
 position: relative;
 float: left;
 top: 100px;
 margin: 10px;
 padding: 0em;
}

#menu_left ul {
 list-style: none;
 margin: 0;
 padding: 0;
}

#menu_left ul li {
 margin: 0;
 padding: 4px;


}
/* LINBOX LEFT MENU */

.revhistory {
    background-color: #F2F2F2;
    border: 1px solid #CCC;
}

.revhistory td {
    border: 1px solid #CCC;
}

.screen {
 background-color: #FFEEDD;
 padding: 2em;
 -moz-border-radius: 8px;
 -khtml-border-radius: 8px;
 border-radius: 8px;
}

.note {
  background-color: #DDEEFF;
  margin: 2em;
  margin-left: auto;
  margin-right: auto;
  width: 80% !important;
  min-height: 40px;
  clear: both;
  text-align: justify;
  vertical-align: middle;
  border-collapse: collapse;
  padding: 0.5em 1em 0.5em 36px;
  background-position: 5px 0.5em;
  background-repeat: no-repeat;
  -moz-border-radius: 8px;
  -khtml-border-radius: 8px;
  border-radius: 8px;
}

</style>


<div id="logolinbox"><img src="http://lds.linbox.org/custom/logoLinbox_navbar.gif" alt="linbox"/></div

<div id="header">
  <a id="logo" href="http://www.linbox.com"><img src="http://lds.linbox.org/trac/linbox.png"
      width="236" height="73"
      alt="Linbox - FAS" /></a>
</div>

<div id="metanav" class="nav">
    &nbsp;
</div>

<div id="mainnav" class="nav" style="overflow: none;">
    &nbsp;
</div>

<div id="main">
<div id="content">
  """]
]



def usage():
    print str(sys.argv[0])+" <input-file> <ouput-file>"


def convert(handleopen, handlewrite):
    global replace_arr
    lines  = handleopen.readlines()
    for i in lines:
        for replace in replace_arr:
            i = i.replace(replace[0],replace[1])
        handlewrite.write(i)


if __name__ == "__main__":
    #verify argument list
    if len(sys.argv)!=3:
        usage()
        sys.exit(0)

    #try opening file
    try:
        filer = open(sys.argv[1],'r')
    except IOError, e:
        print "file "+str(sys.argv[0])+" not exist"
        sys.exit(1)

    #try writing file
    try:
        filew = open(sys.argv[2],'w')
    except IOError, e:
        print "cannot write file "+str(sys.argv[1])
        sys.exit(2)

    convert(filer,filew)

    filer.close()
    filew.close()

