#!/usr/bin/python
import sys

replace_arr = [
["""border="1" """,""],
[ "</head> ","""<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>"""],

[ "</body>" , """
</div>
</div>
<!-- linbox footer section -->
<div id="linbox_footer" class="small">
<!--
  <div class="left" style="margin:0px 4px 0px 4px;">

    <span style="font-weight:bold;">Mandriva</span>: +33 (0)3 87 50 87 90 -
    <a href="mailto:info&#64;linbox.com">info&#64;linbox.com</a>
  </div>
  -->
  <div class="right" style="margin:0px 4px 0px 4px;">&copy;&nbsp; 2007 Mandriva Linux&nbsp;</div><br/>
</div
</body>"""],

[ "<body>" , """<body>  <style type="text/css">
@import url("http://193-19-217-4.ovanet.net/custom/css/linbox.css");

</style>


<div id="logolinbox"><img src="http://mds.mandriva.org/custom/mandriva.png" alt="mandriva"/></div

<div id="header">
  <a id="logo" href="http://www.linbox.com"><img src="http://lds.linbox.org/trac/linbox.png"
      width="236" height="73"
      alt="Linbox - FAS" /></a>
</div>

<div id="metanav" class="nav">
    &nbsp;
</div>

<div id="mainnav" class="nav" style="overflow: none;">
    &nbsp;
</div>

<div id="main">
<div id="content">
  """]
]



def usage():
    print str(sys.argv[0])+" <input-file> <ouput-file>"


def convert(handleopen, handlewrite):
    global replace_arr
    lines  = handleopen.readlines()
    for i in lines:
        for replace in replace_arr:
            i = i.replace(replace[0],replace[1])
        handlewrite.write(i)


if __name__ == "__main__":
    #verify argument list
    if len(sys.argv)!=3:
        usage()
        sys.exit(0)

    #try opening file
    try:
        filer = open(sys.argv[1],'r')
    except IOError, e:
        print "file "+str(sys.argv[0])+" not exist"
        sys.exit(1)

    #try writing file
    try:
        filew = open(sys.argv[2],'w')
    except IOError, e:
        print "cannot write file "+str(sys.argv[1])
        sys.exit(2)

    convert(filer,filew)

    filer.close()
    filew.close()

